import { expect, test } from '../helpers/fixtures.ts'
import { openShell, promptLine } from '../helpers/shell.ts'

test.beforeEach(async ({ target }) => {
  await target.resetTmux()
})

test('(T8) Dictation editor sends reviewed text once through terminal paste', async ({ ui, target }) => {
  const name = await openShell(ui, target, 'e2e-dictation')
  await ui.page.getByRole('button', { name: 'Terminal actions' }).click()
  await ui.page.getByRole('menuitem', { name: 'Dictation' }).click()
  const dialog = ui.page.getByRole('dialog', { name: 'Dictation' })
  await dialog.getByRole('textbox', { name: 'Dictation text' }).fill('echo dictation-once')
  await dialog.getByRole('button', { name: 'Send' }).click()
  await expect.poll(() => promptLine(target, name)).toMatch(/echo dictation-once$/)
  await ui.page.keyboard.press('Enter')
  await expect.poll(() => target.capture(name)).toContain('dictation-once')
  await expect(dialog).toBeHidden()
})

test('(T8) Returning from background does not automatically refocus the terminal', async ({ ui, target }) => {
  const name = await openShell(ui, target, 'e2e-focus-return')
  const input = ui.page.getByRole('textbox', { name: 'Terminal input' })
  await input.focus()
  await ui.page.evaluate(() => {
    Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'hidden' })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(input).not.toBeFocused()
  await ui.page.evaluate(() => {
    Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'visible' })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await expect(input).not.toBeFocused()
  await ui.page.getByRole('button', { name: 'Terminal actions' }).click()
  await ui.page.getByRole('menuitem', { name: 'Show keyboard' }).click()
  await expect(input).toBeFocused()
  expect(await target.sessions()).toContain(name)
})

test('(T8) Switching tabs does not automatically open the terminal keyboard', async ({ ui, target }) => {
  const first = await openShell(ui, target, 'e2e-focus-a')
  const second = await openShell(ui, target, 'e2e-focus-b')
  await ui.open()
  await ui.openTerminal(first)
  await ui.openTerminal(second)
  const input = ui.page.getByRole('textbox', { name: 'Terminal input' })
  await input.evaluate((el) => (el as HTMLElement).blur())
  await ui.tab(first).click()
  await expect(input).not.toBeFocused()
  await ui.terminalAction(first, 'Show keyboard')
  await expect(input).toBeFocused()
})

test('(T8) Terminal text snapshot scrolls, selects, and closes', async ({ ui, target }) => {
  await ui.page.setViewportSize({ width: 390, height: 844 })
  const name = await openShell(ui, target, 'e2e-snapshot', async (session) => {
    await target.tmux('send-keys', '-t', '=' + session + ':', "printf '\\033[31molder-marker\\033[0m\\n'; printf '%0200d\\n' 1; seq 1 300; echo history-complete", 'Enter')
    await expect.poll(() => target.capture(session)).toContain('history-complete')
  })
  await ui.page.getByRole('button', { name: 'Terminal actions' }).click()
  await ui.page.getByRole('menuitem', { name: 'View terminal text' }).click()
  const dialog = ui.page.getByRole('dialog', { name: 'Terminal text view' })
  const snapshot = dialog.getByRole('region', { name: 'Terminal text' })
  await expect(snapshot).toContainText('older-marker')
  const text = await snapshot.innerText()
  expect(text).toContain('1')
  expect(text).toContain('300')
  expect(await snapshot.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  expect(await snapshot.evaluate((el) => el.scrollHeight > el.clientHeight)).toBe(true)
  await snapshot.evaluate((el) => { el.scrollTop = 0 })
  await expect(snapshot).toHaveJSProperty('scrollTop', 0)
  expect(await target.display(name, '#{pane_in_mode}')).toBe('0')
  await expect(snapshot.locator('canvas, textarea')).toHaveCount(0)
  await snapshot.evaluate((el) => { el.scrollTop = el.scrollHeight })
  await snapshot.focus()
  await ui.page.keyboard.press('Control+A')
  expect(await ui.page.evaluate(() => getSelection()?.toString())).toContain('1')
  expect(await ui.page.evaluate(() => getSelection()?.toString())).toContain('300')
  await dialog.getByRole('button', { name: 'Close terminal view' }).click()
  await expect(dialog).toBeHidden()
})

test('(T8) Terminal text includes shell history under a full-screen app', async ({ ui, target }) => {
  await ui.page.setViewportSize({ width: 390, height: 844 })
  await openShell(ui, target, 'e2e-snapshot-alt', async (session) => {
    await target.tmux('send-keys', '-t', '=' + session + ':', "seq 1 300; printf 'shell-%s\\n' marker; printf '\\033[?1049h\\033[Happ-screen-%s\\n' marker; sleep 600", 'Enter')
    await expect.poll(() => target.display(session, '#{alternate_on}')).toBe('1')
  })
  await ui.page.getByRole('button', { name: 'Terminal actions' }).click()
  await ui.page.getByRole('menuitem', { name: 'View terminal text' }).click()
  const snapshot = ui.page.getByRole('dialog', { name: 'Terminal text view' }).getByRole('region', { name: 'Terminal text' })
  await expect(snapshot).toContainText('app-screen-marker')
  const text = await snapshot.innerText()
  expect(text.indexOf('shell-marker')).toBeGreaterThan(text.indexOf('\n300\n'))
  expect(text.indexOf('app-screen-marker')).toBeGreaterThan(text.indexOf('shell-marker'))
  expect(text).not.toMatch(/ +\n/)
  expect(await snapshot.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
})
