package sshx

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// HostAlias is the ssh config alias of the built-in host machine; its pinned
// keys are stored under the same name (HostKeyAlias).
const HostAlias = "hostbud-host"

// renderConfig returns the ssh config. OpenSSH uses the first value it finds
// for each option, so the host and server entries come first and the app
// defaults (Host *) last. Target fields are validated (ValidateTarget), so
// they hold no whitespace or newlines.
func renderConfig(c Config, targets []Target) string {
	var b strings.Builder
	b.WriteString("# Generated by hostbud on startup; do not edit.\n\n")
	b.WriteString("# 1. Built-in host machine\n")
	fmt.Fprintf(&b, "Host %s\n", HostAlias)
	fmt.Fprintf(&b, "  HostName %s\n", c.HostAddr)
	if c.HostPort != 0 {
		fmt.Fprintf(&b, "  Port %d\n", c.HostPort)
	}
	fmt.Fprintf(&b, "  User %s\n", c.HostUser)
	fmt.Fprintf(&b, "  HostKeyAlias %s\n", HostAlias)
	if len(targets) > 0 {
		b.WriteString("\n# 2. Servers added in the UI (pinned keys under their alias)\n")
	}
	for _, t := range targets {
		fmt.Fprintf(&b, "Host %s\n", t.Alias)
		fmt.Fprintf(&b, "  HostName %s\n", t.HostName)
		fmt.Fprintf(&b, "  Port %d\n", t.Port)
		fmt.Fprintf(&b, "  User %s\n", t.User)
		fmt.Fprintf(&b, "  HostKeyAlias %s\n", t.Alias)
	}
	b.WriteString("\n# 3. App defaults — last, so earlier entries win\n")
	b.WriteString("Host *\n")
	b.WriteString("  ControlMaster auto\n")
	fmt.Fprintf(&b, "  ControlPath %s\n", filepath.Join(c.Dir, "cm", "%C"))
	b.WriteString("  ControlPersist 10m\n")
	b.WriteString("  ServerAliveInterval 15\n")
	b.WriteString("  ServerAliveCountMax 3\n")
	b.WriteString("  ConnectTimeout " + strconv.Itoa(connectTimeoutSeconds) + "\n")
	fmt.Fprintf(&b, "  UserKnownHostsFile %s\n", filepath.Join(c.Dir, "known_hosts"))
	b.WriteString("  GlobalKnownHostsFile /dev/null\n")
	b.WriteString("  StrictHostKeyChecking yes\n")
	b.WriteString("  UpdateHostKeys no\n")
	b.WriteString("  BatchMode yes\n")
	return b.String()
}

const connectTimeoutSeconds = 10

// knownHosts reads every *.pub file in dir and returns known_hosts lines
// pinning those keys to HostAlias. Only public keys are read.
func knownHosts(dir string) (string, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.pub"))
	if err != nil {
		return "", err
	}
	sort.Strings(paths)
	var b strings.Builder
	for _, p := range paths {
		data, err := os.ReadFile(p) //nolint:gosec // p comes from a glob of the configured keys dir
		if err != nil {
			return "", fmt.Errorf("read host key %s: %w", filepath.Base(p), err)
		}
		sc := bufio.NewScanner(bytes.NewReader(data))
		for sc.Scan() {
			fields := strings.Fields(sc.Text())
			if len(fields) < 2 || strings.HasPrefix(fields[0], "#") {
				continue
			}
			if !isKeyType(fields[0]) {
				return "", fmt.Errorf("host key %s: %q is not a public key type", filepath.Base(p), fields[0])
			}
			fmt.Fprintf(&b, "%s %s %s\n", HostAlias, fields[0], fields[1])
		}
	}
	if b.Len() == 0 {
		return "", fmt.Errorf("no SSH host keys found in %s. hostbud pins the host's identity from "+
			"its public host keys: mount /etc/ssh/ssh_host_*_key.pub from the host there "+
			"(see docker-compose.yml) and make sure sshd has generated them", dir)
	}
	return b.String(), nil
}

func isKeyType(t string) bool {
	return strings.HasPrefix(t, "ssh-") || strings.HasPrefix(t, "ecdsa-sha2-") ||
		strings.HasPrefix(t, "sk-ssh-") || strings.HasPrefix(t, "sk-ecdsa-")
}

// targetKnownHosts returns the known_hosts lines pinning each server's
// confirmed keys to its alias.
func targetKnownHosts(targets []Target) string {
	var b strings.Builder
	for _, t := range targets {
		for _, k := range t.Keys {
			fmt.Fprintf(&b, "%s %s %s\n", t.Alias, k.Type, k.Key)
		}
	}
	return b.String()
}

// writeFiles creates Dir, Dir/cm and Dir/cml (0700), known_hosts (the host's
// pinned keys, then the servers') and config.
func writeFiles(c Config, hostKnown string, targets []Target) (configPath string, err error) {
	hosts := hostKnown + targetKnownHosts(targets)
	for _, d := range []string{c.Dir, filepath.Join(c.Dir, "cm"), filepath.Join(c.Dir, longLivedDir)} {
		if err := os.MkdirAll(d, 0o700); err != nil {
			return "", fmt.Errorf("create %s: %w", d, err)
		}
		if err := os.Chmod(d, 0o700); err != nil { //nolint:gosec // a directory: 0700 is owner-only
			return "", err
		}
	}
	configPath = filepath.Join(c.Dir, "config")
	err = errors.Join(
		writeFile(filepath.Join(c.Dir, "known_hosts"), hosts),
		writeFile(configPath, renderConfig(c, targets)),
	)
	return configPath, err
}

// writeFile replaces path atomically with mode 0600.
func writeFile(path, content string) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
